"""
This Python module provides functions related to running the gSpan algorithm for graph mining. 
The module facilitates running the gSpan algorithm with specified input configurations, 
generating gSpan algorithm parameters based on input values, 
and capturing the output patterns generated by the algorithm.
"""

from gspan_mining.config import parser
from gspan_mining.main import main
import sys

def run_gspan(input):
    """
    Run the gSpan algorithm with specified input configuration.

    :param input: String containing command-line arguments for gSpan.
    :return: None
    """
    FLAGS, _ = parser.parse_known_args(args=input.split())
    file_name = 'input/outputpatterns.txt'
    try: 
        with open(file_name, 'a', encoding='utf-8') as my_file:
            sys.stdout = my_file
            gs = main(FLAGS)
        with open(file_name, 'r') as fd:
            data = fd.read()
            list_ = data.split("\n")
    finally:
        sys.stdout = sys.__stdout__ 

def gsparameters(values):
    """
    Generate gSpan algorithm parameters based on input values.

    :param values: Tuple containing (min_support, min_num_vertices) values.
    :return: String of gSpan algorithm parameters.
    """
    i,j = values
    parameters = f'-s {i} -l {j} -d False -v False -p False -w True ./input/graphs.data'
    return parameters

